@echo off
echo Starting Book-Ur-Seat Application...

echo Starting Backend...
start cmd /k "cd backend && npm run dev"

echo Waiting for backend to initialize...
timeout /t 3 /nobreak > nul

echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"

echo Waiting for frontend to initialize...
timeout /t 3 /nobreak > nul

echo Opening application in browser...
start http://localhost:5173

echo Application start commands issued!
